INSERT INTO Nationalities (ID, Name, Code) VALUES (1,'Afghanistan', 'AFG');
INSERT INTO Nationalities (ID, Name, Code) VALUES (2,'Åland Islands', 'ALA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (3,'Albania', 'ALB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (4,'Algeria', 'DZA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (5,'American Samoa', 'ASM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (6,'Andorra', 'AND');
INSERT INTO Nationalities (ID, Name, Code) VALUES (7,'Angola', 'AGO');
INSERT INTO Nationalities (ID, Name, Code) VALUES (8,'Anguilla', 'AIA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (9,'Antarctica', 'ATA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (10,'Antigua and Barbuda', 'ATG');
INSERT INTO Nationalities (ID, Name, Code) VALUES (11,'Argentina', 'ARG');
INSERT INTO Nationalities (ID, Name, Code) VALUES (12,'Armenia', 'ARM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (13,'Aruba', 'ABW');
INSERT INTO Nationalities (ID, Name, Code) VALUES (14,'Australia', 'AUS');
INSERT INTO Nationalities (ID, Name, Code) VALUES (15,'Austria', 'AUT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (16,'Azerbaijan', 'AZE');
INSERT INTO Nationalities (ID, Name, Code) VALUES (17,'Bahamas', 'BHS');
INSERT INTO Nationalities (ID, Name, Code) VALUES (18,'Bahrain', 'BHR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (19,'Bangladesh', 'BGD');
INSERT INTO Nationalities (ID, Name, Code) VALUES (20,'Barbados', 'BRB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (21,'Belarus', 'BLR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (22,'Belgium', 'BEL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (23,'Belize', 'BLZ');
INSERT INTO Nationalities (ID, Name, Code) VALUES (24,'Benin', 'BEN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (25,'Bermuda', 'BMU');
INSERT INTO Nationalities (ID, Name, Code) VALUES (26,'Bhutan', 'BTN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (27,'Bolivia (Plurinational State of)', 'BOL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (28,'Bonaire, Sint Eustatius and Saba', 'BES');
INSERT INTO Nationalities (ID, Name, Code) VALUES (29,'Bosnia and Herzegovina', 'BIH');
INSERT INTO Nationalities (ID, Name, Code) VALUES (30,'Botswana', 'BWA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (31,'Bouvet Island', 'BVT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (32,'Brazil', 'BRA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (33,'British Indian Ocean Territory', 'IOT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (34,'Brunei Darussalam', 'BRN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (35,'Bulgaria', 'BGR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (36,'Burkina Faso', 'BFA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (37,'Burundi', 'BDI');
INSERT INTO Nationalities (ID, Name, Code) VALUES (38,'Cabo Verde', 'CPV');
INSERT INTO Nationalities (ID, Name, Code) VALUES (39,'Cambodia', 'KHM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (40,'Cameroon', 'CMR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (41,'Canada', 'CAN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (42,'Cayman Islands', 'CYM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (43,'Central African Republic', 'CAF');
INSERT INTO Nationalities (ID, Name, Code) VALUES (44,'Chad', 'TCD');
INSERT INTO Nationalities (ID, Name, Code) VALUES (45,'Chile', 'CHL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (46,'China', 'CHN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (47,'Christmas Island', 'CXR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (48,'Cocos (Keeling) Islands', 'CCK');
INSERT INTO Nationalities (ID, Name, Code) VALUES (49,'Colombia', 'COL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (50,'Comoros', 'COM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (51,'Congo', 'COG');
INSERT INTO Nationalities (ID, Name, Code) VALUES (52,'Congo (Democratic Republic of the)', 'COD');
INSERT INTO Nationalities (ID, Name, Code) VALUES (53,'Cook Islands', 'COK');
INSERT INTO Nationalities (ID, Name, Code) VALUES (54,'Costa Rica', 'CRI');
INSERT INTO Nationalities (ID, Name, Code) VALUES (55,'Côte d''Ivoire', 'CIV');
INSERT INTO Nationalities (ID, Name, Code) VALUES (56,'Croatia', 'HRV');
INSERT INTO Nationalities (ID, Name, Code) VALUES (57,'Cuba', 'CUB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (58,'Curaçao', 'CUW');
INSERT INTO Nationalities (ID, Name, Code) VALUES (59,'Cyprus', 'CYP');
INSERT INTO Nationalities (ID, Name, Code) VALUES (60,'Czech Republic', 'CZE');
INSERT INTO Nationalities (ID, Name, Code) VALUES (61,'Denmark', 'DNK');
INSERT INTO Nationalities (ID, Name, Code) VALUES (62,'Djibouti', 'DJI');
INSERT INTO Nationalities (ID, Name, Code) VALUES (63,'Dominica', 'DMA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (64,'Dominican Republic', 'DOM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (65,'Ecuador', 'ECU');
INSERT INTO Nationalities (ID, Name, Code) VALUES (66,'Egypt', 'EGY');
INSERT INTO Nationalities (ID, Name, Code) VALUES (67,'El Salvador', 'SLV');
INSERT INTO Nationalities (ID, Name, Code) VALUES (68,'Equatorial Guinea', 'GNQ');
INSERT INTO Nationalities (ID, Name, Code) VALUES (69,'Eritrea', 'ERI');
INSERT INTO Nationalities (ID, Name, Code) VALUES (70,'Estonia', 'EST');
INSERT INTO Nationalities (ID, Name, Code) VALUES (71,'Ethiopia', 'ETH');
INSERT INTO Nationalities (ID, Name, Code) VALUES (72,'Falkland Islands (Malvinas)', 'FLK');
INSERT INTO Nationalities (ID, Name, Code) VALUES (73,'Faroe Islands', 'FRO');
INSERT INTO Nationalities (ID, Name, Code) VALUES (74,'Fiji', 'FJI');
INSERT INTO Nationalities (ID, Name, Code) VALUES (75,'Finland', 'FIN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (76,'France', 'FRA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (77,'French Guiana', 'GUF');
INSERT INTO Nationalities (ID, Name, Code) VALUES (78,'French Polynesia', 'PYF');
INSERT INTO Nationalities (ID, Name, Code) VALUES (79,'French Southern Territories', 'ATF');
INSERT INTO Nationalities (ID, Name, Code) VALUES (80,'Gabon', 'GAB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (81,'Gambia', 'GMB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (82,'Georgia', 'GEO');
INSERT INTO Nationalities (ID, Name, Code) VALUES (83,'Germany', 'DEU');
INSERT INTO Nationalities (ID, Name, Code) VALUES (84,'Ghana', 'GHA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (85,'Gibraltar', 'GIB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (86,'Greece', 'GRC');
INSERT INTO Nationalities (ID, Name, Code) VALUES (87,'Greenland', 'GRL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (88,'Grenada', 'GRD');
INSERT INTO Nationalities (ID, Name, Code) VALUES (89,'Guadeloupe', 'GLP');
INSERT INTO Nationalities (ID, Name, Code) VALUES (90,'Guam', 'GUM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (91,'Guatemala', 'GTM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (92,'Guernsey', 'GGY');
INSERT INTO Nationalities (ID, Name, Code) VALUES (93,'Guinea', 'GIN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (94,'Guinea-Bissau', 'GNB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (95,'Guyana', 'GUY');
INSERT INTO Nationalities (ID, Name, Code) VALUES (96,'Haiti', 'HTI');
INSERT INTO Nationalities (ID, Name, Code) VALUES (97,'Heard Island and McDonald Islands', 'HMD');
INSERT INTO Nationalities (ID, Name, Code) VALUES (98,'Holy See', 'VAT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (99,'Honduras', 'HND');
INSERT INTO Nationalities (ID, Name, Code) VALUES (100,'Hong Kong', 'HKG');
INSERT INTO Nationalities (ID, Name, Code) VALUES (101,'Hungary', 'HUN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (102,'Iceland', 'ISL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (103,'India', 'IND');
INSERT INTO Nationalities (ID, Name, Code) VALUES (104,'Indonesia', 'IDN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (105,'Iran (Islamic Republic of)', 'IRN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (106,'Iraq', 'IRQ');
INSERT INTO Nationalities (ID, Name, Code) VALUES (107,'Ireland', 'IRL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (108,'Isle of Man', 'IMN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (109,'Israel', 'ISR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (110,'Italy', 'ITA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (111,'Jamaica', 'JAM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (112,'Japan', 'JPN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (113,'Jersey', 'JEY');
INSERT INTO Nationalities (ID, Name, Code) VALUES (114,'Jordan', 'JOR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (115,'Kazakhstan', 'KAZ');
INSERT INTO Nationalities (ID, Name, Code) VALUES (116,'Kenya', 'KEN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (117,'Kiribati', 'KIR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (118,'Korea (Democratic People''s Republic of)', 'PRK');
INSERT INTO Nationalities (ID, Name, Code) VALUES (119,'Korea (Republic of)', 'KOR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (120,'Kuwait', 'KWT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (121,'Kyrgyzstan', 'KGZ');
INSERT INTO Nationalities (ID, Name, Code) VALUES (122,'Lao People''s Democratic Republic', 'LAO');
INSERT INTO Nationalities (ID, Name, Code) VALUES (123,'Latvia', 'LVA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (124,'Lebanon', 'LBN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (125,'Lesotho', 'LSO');
INSERT INTO Nationalities (ID, Name, Code) VALUES (126,'Liberia', 'LBR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (127,'Libya', 'LBY');
INSERT INTO Nationalities (ID, Name, Code) VALUES (128,'Liechtenstein', 'LIE');
INSERT INTO Nationalities (ID, Name, Code) VALUES (129,'Lithuania', 'LTU');
INSERT INTO Nationalities (ID, Name, Code) VALUES (130,'Luxembourg', 'LUX');
INSERT INTO Nationalities (ID, Name, Code) VALUES (131,'Macao', 'MAC');
INSERT INTO Nationalities (ID, Name, Code) VALUES (132,'Macedonia (the former Yugoslav Republic of)', 'MKD');
INSERT INTO Nationalities (ID, Name, Code) VALUES (133,'Madagascar', 'MDG');
INSERT INTO Nationalities (ID, Name, Code) VALUES (134,'Malawi', 'MWI');
INSERT INTO Nationalities (ID, Name, Code) VALUES (135,'Malaysia', 'MYS');
INSERT INTO Nationalities (ID, Name, Code) VALUES (136,'Maldives', 'MDV');
INSERT INTO Nationalities (ID, Name, Code) VALUES (137,'Mali', 'MLI');
INSERT INTO Nationalities (ID, Name, Code) VALUES (138,'Malta', 'MLT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (139,'Marshall Islands', 'MHL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (140,'Martinique', 'MTQ');
INSERT INTO Nationalities (ID, Name, Code) VALUES (141,'Mauritania', 'MRT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (142,'Mauritius', 'MUS');
INSERT INTO Nationalities (ID, Name, Code) VALUES (143,'Mayotte', 'MYT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (144,'Mexico', 'MEX');
INSERT INTO Nationalities (ID, Name, Code) VALUES (145,'Micronesia (Federated States of)', 'FSM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (146,'Moldova (Republic of)', 'MDA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (147,'Monaco', 'MCO');
INSERT INTO Nationalities (ID, Name, Code) VALUES (148,'Mongolia', 'MNG');
INSERT INTO Nationalities (ID, Name, Code) VALUES (149,'Montenegro', 'MNE');
INSERT INTO Nationalities (ID, Name, Code) VALUES (150,'Montserrat', 'MSR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (151,'Morocco', 'MAR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (152,'Mozambique', 'MOZ');
INSERT INTO Nationalities (ID, Name, Code) VALUES (153,'Myanmar', 'MMR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (154,'Namibia', 'NAM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (155,'Nauru', 'NRU');
INSERT INTO Nationalities (ID, Name, Code) VALUES (156,'Nepal', 'NPL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (157,'Netherlands', 'NLD');
INSERT INTO Nationalities (ID, Name, Code) VALUES (158,'New Caledonia', 'NCL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (159,'New Zealand', 'NZL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (160,'Nicaragua', 'NIC');
INSERT INTO Nationalities (ID, Name, Code) VALUES (161,'Niger', 'NER');
INSERT INTO Nationalities (ID, Name, Code) VALUES (162,'Nigeria', 'NGA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (163,'Niue', 'NIU');
INSERT INTO Nationalities (ID, Name, Code) VALUES (164,'Norfolk Island', 'NFK');
INSERT INTO Nationalities (ID, Name, Code) VALUES (165,'Northern Mariana Islands', 'MNP');
INSERT INTO Nationalities (ID, Name, Code) VALUES (166,'Norway', 'NOR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (167,'Oman', 'OMN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (168,'Pakistan', 'PAK');
INSERT INTO Nationalities (ID, Name, Code) VALUES (169,'Palau', 'PLW');
INSERT INTO Nationalities (ID, Name, Code) VALUES (170,'Palestine, State of', 'PSE');
INSERT INTO Nationalities (ID, Name, Code) VALUES (171,'Panama', 'PAN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (172,'Papua New Guinea', 'PNG');
INSERT INTO Nationalities (ID, Name, Code) VALUES (173,'Paraguay', 'PRY');
INSERT INTO Nationalities (ID, Name, Code) VALUES (174,'Peru', 'PER');
INSERT INTO Nationalities (ID, Name, Code) VALUES (175,'Philippines', 'PHL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (176,'Pitcairn', 'PCN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (177,'Poland', 'POL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (178,'Portugal', 'PRT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (179,'Puerto Rico', 'PRI');
INSERT INTO Nationalities (ID, Name, Code) VALUES (180,'Qatar', 'QAT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (181,'Réunion', 'REU');
INSERT INTO Nationalities (ID, Name, Code) VALUES (182,'Romania', 'ROU');
INSERT INTO Nationalities (ID, Name, Code) VALUES (183,'Russian Federation', 'RUS');
INSERT INTO Nationalities (ID, Name, Code) VALUES (184,'Rwanda', 'RWA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (185,'Saint Barthélemy', 'BLM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (186,'Saint Helena, Ascension and Tristan da Cunha', 'SHN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (187,'Saint Kitts and Nevis', 'KNA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (188,'Saint Lucia', 'LCA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (189,'Saint Martin (French part)', 'MAF');
INSERT INTO Nationalities (ID, Name, Code) VALUES (190,'Saint Pierre and Miquelon', 'SPM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (191,'Saint Vincent and the Grenadines', 'VCT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (192,'Samoa', 'WSM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (193,'San Marino', 'SMR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (194,'Sao Tome and Principe', 'STP');
INSERT INTO Nationalities (ID, Name, Code) VALUES (195,'Saudi Arabia', 'SAU');
INSERT INTO Nationalities (ID, Name, Code) VALUES (196,'Senegal', 'SEN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (197,'Serbia', 'SRB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (198,'Seychelles', 'SYC');
INSERT INTO Nationalities (ID, Name, Code) VALUES (199,'Sierra Leone', 'SLE');
INSERT INTO Nationalities (ID, Name, Code) VALUES (200,'Singapore', 'SGP');
INSERT INTO Nationalities (ID, Name, Code) VALUES (201,'Sint Maarten (Dutch part)', 'SXM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (202,'Slovakia', 'SVK');
INSERT INTO Nationalities (ID, Name, Code) VALUES (203,'Slovenia', 'SVN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (204,'Solomon Islands', 'SLB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (205,'Somalia', 'SOM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (206,'South Africa', 'ZAF');
INSERT INTO Nationalities (ID, Name, Code) VALUES (207,'South Georgia and the South Sandwich Islands', 'SGS');
INSERT INTO Nationalities (ID, Name, Code) VALUES (208,'South Sudan', 'SSD');
INSERT INTO Nationalities (ID, Name, Code) VALUES (209,'Spain', 'ESP');
INSERT INTO Nationalities (ID, Name, Code) VALUES (210,'Sri Lanka', 'LKA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (211,'Sudan', 'SDN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (212,'Suriname', 'SUR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (213,'Svalbard and Jan Mayen', 'SJM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (214,'Swaziland', 'SWZ');
INSERT INTO Nationalities (ID, Name, Code) VALUES (215,'Sweden', 'SWE');
INSERT INTO Nationalities (ID, Name, Code) VALUES (216,'Switzerland', 'CHE');
INSERT INTO Nationalities (ID, Name, Code) VALUES (217,'Syrian Arab Republic', 'SYR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (218,'Taiwan, Province of China[a]', 'TWN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (219,'Tajikistan', 'TJK');
INSERT INTO Nationalities (ID, Name, Code) VALUES (220,'Tanzania, United Republic of', 'TZA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (221,'Thailand', 'THA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (222,'Timor-Leste', 'TLS');
INSERT INTO Nationalities (ID, Name, Code) VALUES (223,'Togo', 'TGO');
INSERT INTO Nationalities (ID, Name, Code) VALUES (224,'Tokelau', 'TKL');
INSERT INTO Nationalities (ID, Name, Code) VALUES (225,'Tonga', 'TON');
INSERT INTO Nationalities (ID, Name, Code) VALUES (226,'Trinidad and Tobago', 'TTO');
INSERT INTO Nationalities (ID, Name, Code) VALUES (227,'Tunisia', 'TUN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (228,'Turkey', 'TUR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (229,'Turkmenistan', 'TKM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (230,'Turks and Caicos Islands', 'TCA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (231,'Tuvalu', 'TUV');
INSERT INTO Nationalities (ID, Name, Code) VALUES (232,'Uganda', 'UGA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (233,'Ukraine', 'UKR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (234,'United Arab Emirates', 'ARE');
INSERT INTO Nationalities (ID, Name, Code) VALUES (235,'United Kingdom of Great Britain and Northern Ireland', 'GBR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (236,'United States of America', 'USA');
INSERT INTO Nationalities (ID, Name, Code) VALUES (237,'United States Minor Outlying Islands', 'UMI');
INSERT INTO Nationalities (ID, Name, Code) VALUES (238,'Uruguay', 'URY');
INSERT INTO Nationalities (ID, Name, Code) VALUES (239,'Uzbekistan', 'UZB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (240,'Vanuatu', 'VUT');
INSERT INTO Nationalities (ID, Name, Code) VALUES (241,'Venezuela (Bolivarian Republic of)', 'VEN');
INSERT INTO Nationalities (ID, Name, Code) VALUES (242,'Viet Nam', 'VNM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (243,'Virgin Islands (British)', 'VGB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (244,'Virgin Islands (U.S.)', 'VIR');
INSERT INTO Nationalities (ID, Name, Code) VALUES (245,'Wallis and Futuna', 'WLF');
INSERT INTO Nationalities (ID, Name, Code) VALUES (246,'Western Sahara', 'ESH');
INSERT INTO Nationalities (ID, Name, Code) VALUES (247,'Yemen', 'YEM');
INSERT INTO Nationalities (ID, Name, Code) VALUES (248,'Zambia', 'ZMB');
INSERT INTO Nationalities (ID, Name, Code) VALUES (249,'Zimbabwe', 'ZWE');
